### ISSUE TITLE
Was support for the lodash compatibility mode dropped?

### ISSUE THREAD

**Issue by mattmenefee** [rh/lodash-rails#5]
Looks like it was removed when lodash was updated to v3.2.0.  Any particular reason?

**Comment by rh** [comment]
The reason was that I thought only one build was directly supported by lodash, see https://cdnjs.com/libraries/lodash.js. But lodash.com still offers the compatibility build and http://www.jsdelivr.com/ does as well (although it is not up-to-date at the moment.)

So I've restored the compatibility build and released it as v3.3.1.1.

Thanks for noticing.
